<?php 
 $data=array (
  'catalogs' => 
  array (
    0 => 'jatc',
    1 => 'jmtc',
  ),
  'jatc' => 
  array (
    0 => 
    array (
      'id' => '',
      'name' => 'ja_appolio',
      'title' => 'JA Appolio',
      'desc' => 'Dec, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_appolio/',
      'image' => 'images/products/ja/appolio_featured.jpg',
      'tags' => 'rtl language easyblog joomla 2.5 joomla 3 responsive showcase',
      'classes' => 'featured',
      'rating' => '4.6',
      'downloads' => '11766',
      'badge' => 'premium',
    ),
    1 => 
    array (
      'id' => '',
      'name' => 'ja_obelisk',
      'title' => 'JA Obelisk',
      'desc' => 'Nov, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_obelisk/',
      'image' => 'images/products/ja/obelisk.jpg',
      'tags' => 'rtl language easyblog joomla 2.5 joomla 3 responsive movie',
      'classes' => '',
      'rating' => '3.9',
      'downloads' => '4775',
      'badge' => 'j25 j30',
    ),
    2 => 
    array (
      'id' => '',
      'name' => 'ja_magz',
      'title' => 'JA Magz',
      'desc' => 'Oct, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_magz',
      'image' => 'images/products/ja/magz.jpg',
      'tags' => 'joomla-25 joomla-3 responsive',
      'classes' => '',
      'rating' => '4.6',
      'downloads' => '2137',
      'badge' => 'j25 j30',
    ),
    3 => 
    array (
      'id' => '',
      'name' => 'ja_muzic',
      'title' => 'JA Muzic',
      'desc' => 'Sep, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_muzic',
      'image' => 'images/products/ja/muzic.jpg',
      'tags' => 'joomla 2.5 joomla 3 responsive',
      'classes' => '',
      'rating' => '4.2',
      'downloads' => '14803',
      'badge' => 'j25 j30',
    ),
    4 => 
    array (
      'id' => '',
      'name' => 'ja_fixel',
      'title' => 'JA Fixel',
      'desc' => 'August, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_fixel/',
      'image' => 'images/products/ja/fixel.jpg',
      'tags' => 'responsive joomla-25 joomla-3 easyblog-j25',
      'classes' => '',
      'rating' => '4.1',
      'downloads' => '13798',
      'badge' => 'j25 j30',
    ),
    5 => 
    array (
      'id' => '',
      'name' => 'ja_beranis',
      'title' => 'JA Beranis',
      'desc' => 'July, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_beranis/',
      'image' => 'images/products/ja/beranis.jpg',
      'tags' => 'rtl language',
      'classes' => '',
      'rating' => '3.9',
      'downloads' => '10098',
      'badge' => 'j25 j30',
    ),
    6 => 
    array (
      'id' => '',
      'name' => 'ja_smashboard',
      'title' => 'JA SmashBoard',
      'desc' => 'June, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_smashboard/',
      'image' => 'images/products/ja/smashboard.jpg',
      'tags' => 'rtl language',
      'classes' => '',
      'rating' => '3.9',
      'downloads' => '3054',
      'badge' => 'j25 j30',
    ),
    7 => 
    array (
      'id' => '',
      'name' => 'ja_hawkstore',
      'title' => 'JA Hawstore',
      'desc' => 'May, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_hawkstore/',
      'image' => 'images/products/ja/hawkstore.jpg',
      'tags' => 'e-commerce joomla-25',
      'classes' => '',
      'rating' => '4.1',
      'downloads' => '24168',
      'badge' => 'j25 j30',
    ),
    8 => 
    array (
      'id' => '',
      'name' => 'ja_fubix',
      'title' => 'JA Fubix',
      'desc' => 'Apr, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_fubix/',
      'image' => 'images/products/ja/fubix.jpg',
      'tags' => 'responsive joomla-25 joomla-3',
      'classes' => '',
      'rating' => '3',
      'downloads' => '4309',
      'badge' => 'j25 j30',
    ),
    9 => 
    array (
      'id' => '',
      'name' => 'ja_argo',
      'title' => 'JA Argo',
      'desc' => 'Mar, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_argo/',
      'image' => 'images/products/ja/argo.jpg',
      'tags' => 'responsive joomla-25 joomla-3',
      'classes' => '',
      'rating' => '3.9',
      'downloads' => '4747',
      'badge' => 'j25 j30',
    ),
    10 => 
    array (
      'id' => '',
      'name' => 'ja_mitius',
      'title' => 'JA Mitius',
      'desc' => 'Feb, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_mitius/',
      'image' => 'images/products/ja/mitius.jpg',
      'tags' => 'responsive joomla-25 joomla-3',
      'classes' => '',
      'rating' => '3.7',
      'downloads' => '40143',
      'badge' => 'j25 j30',
    ),
    11 => 
    array (
      'id' => '',
      'name' => 'ja_onepage',
      'title' => 'JA Onepage',
      'desc' => 'Jan, 2013',
      'year' => '2013',
      'url' => 'http://joomla-templates.joomlart.com/ja_onepage/',
      'image' => 'images/products/ja/onepage.jpg',
      'tags' => 'responsive joomla-25',
      'classes' => '',
      'rating' => '2.9',
      'downloads' => '28513',
      'badge' => 'j25 j30',
    ),
    12 => 
    array (
      'id' => '',
      'name' => 'ja_mero',
      'title' => 'JA Mero',
      'desc' => 'Dec, 2012',
      'year' => '2012',
      'url' => 'http://joomla-templates.joomlart.com/ja_mero/',
      'image' => 'images/products/ja/mero.jpg',
      'tags' => 'rtl language',
      'classes' => '',
      'rating' => '3.4',
      'downloads' => '19938',
      'badge' => 'j25 j30',
    ),
    13 => 
    array (
      'id' => '',
      'name' => 'ja_brisk',
      'title' => 'JA Brisk',
      'desc' => 'Nov, 2012',
      'year' => '2012',
      'url' => 'http://joomla-templates.joomlart.com/ja_brisk/',
      'image' => 'images/products/ja/brisk.jpg',
      'tags' => 'responsive joomla-25 joomla-3',
      'classes' => '',
      'rating' => '3.2',
      'downloads' => '13967',
      'badge' => 'j25 j30',
    ),
  ),
  'jatc-tags' => 
  array (
    'responsive' => 10,
    'joomla-25' => 8,
    'joomla' => 6,
    'joomla-3' => 6,
    'language' => 5,
    'rtl' => 5,
    3 => 3,
    '2.5' => 3,
    'easyblog' => 2,
    'e-commerce' => 1,
    'easyblog-j25' => 1,
    'movie' => 1,
    'showcase' => 1,
  ),
  'jatc-years' => 
  array (
    2013 => 12,
    2012 => 2,
  ),
  'jmtc' => 
  array (
    0 => 
    array (
      'id' => '',
      'name' => 'jm_megamall',
      'title' => 'JM Megamall',
      'desc' => 'December, 2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_megamall',
      'image' => 'images/products/jm/megamall_featured.jpg',
      'tags' => 'responsive',
      'classes' => 'featured',
      'rating' => '3.5',
      'downloads' => '47',
      'badge' => '',
    ),
    1 => 
    array (
      'id' => '',
      'name' => 'jm_bookshop',
      'title' => 'JM Bookshop',
      'desc' => 'November, 2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_bookshop',
      'image' => 'images/products/jm/bookshop.jpg',
      'tags' => 'responsive book',
      'classes' => '',
      'rating' => '4.1',
      'downloads' => '',
      'badge' => '',
    ),
    2 => 
    array (
      'id' => '',
      'name' => 'jm_gamestore',
      'title' => 'JM Gamestore',
      'desc' => 'October, 2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_gamestore',
      'image' => 'images/products/jm/gamestore_small.jpg',
      'tags' => 'responsive digital',
      'classes' => '',
      'rating' => '5',
      'downloads' => '',
      'badge' => '',
    ),
    3 => 
    array (
      'id' => '',
      'name' => 'jm_monsieur',
      'title' => 'JM Monsieur',
      'desc' => 'September,2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_monsieur',
      'image' => 'images/products/jm/monsieur.jpg',
      'tags' => 'responsive',
      'classes' => '',
      'rating' => '3.1',
      'downloads' => '338',
      'badge' => '',
    ),
    4 => 
    array (
      'id' => '',
      'name' => 'jm_sporty',
      'title' => 'JM Sporty',
      'desc' => 'July,2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_sporty',
      'image' => 'images/products/jm/sporty.jpg',
      'tags' => 'fashion',
      'classes' => '',
      'rating' => '2.9',
      'downloads' => '231',
      'badge' => '',
    ),
    5 => 
    array (
      'id' => '',
      'name' => 'jm_lingerie',
      'title' => 'JM Lingerie',
      'desc' => 'June,2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_lingerie',
      'image' => 'images/products/jm/lingerie.jpg',
      'tags' => 'fashion responsive',
      'classes' => '',
      'rating' => '3.8',
      'downloads' => '246',
      'badge' => '',
    ),
    6 => 
    array (
      'id' => '',
      'name' => 'jm_hawkstore',
      'title' => 'JM Hawkstore',
      'desc' => 'April, 2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_hawkstore',
      'image' => 'images/products/jm/hawkstore.jpg',
      'tags' => '',
      'classes' => '',
      'rating' => '4',
      'downloads' => '165',
      'badge' => '',
    ),
    7 => 
    array (
      'id' => '',
      'name' => 'jm_mago',
      'title' => 'JM Mago',
      'desc' => 'March, 2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_mago',
      'image' => 'images/products/jm/mago.jpg',
      'tags' => '',
      'classes' => '',
      'rating' => '3.8',
      'downloads' => '342',
      'badge' => '',
    ),
    8 => 
    array (
      'id' => '',
      'name' => 'jm_flannel',
      'title' => 'JM Flannel',
      'desc' => 'Feb, 2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_flannel',
      'image' => 'images/products/jm/flannel.jpg',
      'tags' => 'responsive digital',
      'classes' => '',
      'rating' => '3.8',
      'downloads' => '479',
      'badge' => '',
    ),
    9 => 
    array (
      'id' => '20389',
      'name' => 'jm_jasmine',
      'title' => 'JM Jasmine',
      'desc' => 'Jan,2013',
      'year' => '2013',
      'url' => 'http://magento-themes.joomlart.com/jm_jasmine',
      'image' => 'images/products/jm/jasmine.jpg',
      'tags' => '',
      'classes' => '',
      'rating' => '4.5',
      'downloads' => '280',
      'badge' => '',
    ),
    10 => 
    array (
      'id' => '',
      'name' => 'jm_neros',
      'title' => 'JM Neros',
      'desc' => 'Dec, 2012',
      'year' => '2012',
      'url' => 'http://magento-themes.joomlart.com/jm_neros',
      'image' => 'images/products/jm/neros.jpg',
      'tags' => 'responsive digital',
      'classes' => '',
      'rating' => '3.5',
      'downloads' => '362',
      'badge' => '',
    ),
    11 => 
    array (
      'id' => '',
      'name' => 'jm_wall',
      'title' => 'JM Wall',
      'desc' => 'Nov,2012',
      'year' => '2012',
      'url' => 'http://magento-themes.joomlart.com/jm_wall',
      'image' => 'images/products/jm/wall.jpg',
      'tags' => '',
      'classes' => '',
      'rating' => '4.3',
      'downloads' => '434',
      'badge' => '',
    ),
  ),
  'jmtc-tags' => 
  array (
    'responsive' => 7,
    'digital' => 3,
    'fashion' => 2,
    'book' => 1,
  ),
  'jmtc-years' => 
  array (
    2013 => 10,
    2012 => 2,
  ),
);
